"""Phase 5 Pydantic schemas for structured execution metadata.

Additive, backward-compatible with the Phase 1-4 execution contracts.
"""
from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, List, Literal
from enum import Enum
import uuid


class ExecutionStatus(str, Enum):
    PENDING = "pending"
    PASS = "pass"
    FAIL = "fail"
    ERROR = "error"
    SKIPPED = "skipped"


class ExecutionMode(str, Enum):
    """Execution mode inferred from the request; serial if not specified."""
    SERIAL = "serial"
    PARALLEL = "parallel"


class AttemptRecord(BaseModel):
    """Structured record for a **single execution attempt** of a test case."""
    attempt: int = Field(..., description="1-based attempt number")
    started_at: float = Field(..., description="Unix timestamp for the attempt start")
    completed_at: Optional[float] = Field(None, description="Unix timestamp for the attempt completion")
    duration: Optional[float] = Field(None, description="Attempt duration in seconds")
    status: ExecutionStatus = Field(..., description="PASS / FAIL / ERROR / SKIPPED")
    details: Optional[str] = Field(None, description="Status detail / exception message")


class RunInfo(BaseModel):
    """High-level execution metadata attached to every run."""
    run_id: str = Field(..., description="Unique identifier for the execution")
    project_id: Optional[str] = Field(None, description="Project identifier (if applicable)")
    started_at: float = Field(..., description="Unix epoch of run start")
    completed_at: Optional[float] = Field(None, description="Unix epoch of run completion")
    attempts: int = Field(..., ge=1, description="Number of attempts executed")
    max_attempts: int = Field(..., ge=1, description="Configured maximum allowed attempts")
    mode: ExecutionMode = Field(ExecutionMode.SERIAL, description="Execution mode")
    logs: List[Dict[str, Any]] = Field(default_factory=list, description="Per-attempt log records")
    artifacts: List[Dict[str, Any]] = Field(default_factory=list, description="Artifacts generated by execution")

class ArtifactInfo(BaseModel):
    """Typed representation of an execution artifact."""
    artifact_type: Literal["screenshot", "file", "log"] = Field(..., description="Artifact type")
    path: str = Field(..., description="Path at which the artifact is stored")
    test_case_id: Optional[str] = Field(None, description="Associated test case ID (if applicable)")
    attempt: Optional[int] = Field(None, description="Attached attempt number")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Optional artifact metadata")

class RunSummary(BaseModel):
    """Structured Phase 5 run summary."""
    run_id: str = Field(..., description="Unique run identifier")
    total: int = Field(..., description="Total configured test cases")
    passed: int = Field(..., description="Passed test case count")
    failed: int = Field(..., description="Failed test case count")
    errors: int = Field(..., description="Errored test case count")
    skipped: int = Field(..., description="Skipped test case count")
    total_duration: float = Field(0.0, description="Total execution duration in seconds")